name: ecommercecourse
description: Ecommerce App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  auto_animated: ^3.0.1
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.5
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get: ^4.6.1
  google_maps_flutter: ^2.1.5
  google_sign_in: ^6.1.0
  grouped_list: ^5.1.2
  http: ^0.13.4
  image_picker: ^0.8.7+4
  image_pickers: ^2.0.0+2
  intl: ^0.17.0
  jiffy: ^5.0.0
  lottie: ^2.3.2
  path: ^1.8.0
  qr_flutter: ^4.0.0
  responsive_builder: ^0.6.4
  scan: ^1.6.0
  shared_preferences: ^2.0.15
  show_up_animation: ^2.0.0
  sqflite: ^2.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
